### ISSUE TITLE
大佬，问下电视剧播放源是哪里来的呀

### ISSUE THREAD

**Issue by zhugezifang** [jiaozhongy/video-free#1]

**Comment by jiaozhongy** [comment]
> _No description provided._

有很多采集的资源api 都是免费的    
比如我用的https://hongniuziyuan.com/ 红牛资源站这种    
应该也能搞tvbox的 你有啥想法  可以聊聊

**Comment by zhugezifang** [comment]
> > _No description provided._
> 
> 有很多采集的资源api 都是免费的 比如我用的https://hongniuziyuan.com/ 红牛资源站这种 应该也能搞tvbox的 你有啥想法 可以聊聊

好像播放有点卡，看了看里面的源，网站是你自己搭建的吗

**Comment by jiaozhongy** [comment]
> > > _未提供描述。_
> > 
> > 
> > 有很多采集的资源api都是免费的比如我用的https://hongniuziyuan.com/红牛资源站这种应该也能搞电视盒你有啥想法可以聊聊
> 
> 好像有点卡，看看里面的来源，网站是你自己搭建的

卡的话可以换换线路之类的，资源不在我的服务器，通过播放器的协议远程去解析的，我这边只是保存了解析地址，网站是用的cms模板  后台也有很多
