### ISSUE TITLE
https://hongniuziyuan.com/这个网站打不开呀 

### ISSUE THREAD

**Issue by yang-chun** [jiaozhongy/video-free#2]

**Comment by jiaozhongy** [comment]
> _No description provided._

![image](https://github.com/jiaozhongy/video-free/assets/68053569/4cc8d22a-01cc-4687-946e-626e6629c1da)
我关了梯子也能打开呀 你打开它干啥，他是用来采集的，我的网站是https://tv.loufubao.com

**Comment by yang-chun** [comment]
找这个api

**Comment by jiaozhongy** [comment]
https://www.hongniuzy2.com/api.php/provide/vod/from/hnm3u8/at/json/?ac=videolist&pg=&h=24   喏

**Comment by yang-chun** [comment]
这个有文档吗

**Comment by yang-chun** [comment]
比如搜索传什么

**Comment by jiaozhongy** [comment]
基本都是cms插件采集  没得文档  你找个cms后台搭起来  然后就可以采集当天 、每周的资源， 好像没有关键词的搜索

**Comment by jiaozhongy** [comment]
![image](https://github.com/jiaozhongy/video-free/assets/68053569/72766507-7a71-4ede-b85e-6c9a7d5266ae)
界面长这样子

**Comment by yang-chun** [comment]
意思就是 这个采集的就是当天的 然后自己存下来 历史的是没有的是吧

**Comment by jiaozhongy** [comment]
可以采集全部， 他给你返回了有多少页，自己循环 ，我这个是插件集成好了

**Comment by yang-chun** [comment]
好的 谢谢大佬
